name = "Meldworks"
author = "Deveyus"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f296cec6c4a4264450d613328f67830065a440b6775ae7012df11af495f01d18"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"

[options]
acceptable-game-versions = ["1.20", "1.20.2", "1.20.4"]
